### ISSUE TITLE
Code Review #2

### ISSUE THREAD

**Issue by swarnimsinha** [mingzicao/601-BSRAPP-CampusPin#11]
I see a lot of improvements that you guys have made since the last code review (removing the redundant files, changing the code structure, etc).
Here are some things that I noticed which you may fix.
1) There are two Android folders - CampusPin and CampusPin_V1.0 and there is no mention which one is the updated one. If you are using one for debugging, then moving it in an older branch would more sense.
2) In the Android application, there are some comments which aren't necessarily useful while some functions have no comments at all.
3) In almost all of the files, there isn't a description that what the code is supposed to do. You guys can add docstrings on your python files to let others know what the functionality of the code is.

Good job on updating the README.MD file and adding the challenges. It really helps.

**Comment by markshibu** [comment]
Thanks a lot!
