### ISSUE TITLE
Code Review#2

### ISSUE THREAD

**Issue by zzxiang8752** [mingzicao/601-BSRAPP-CampusPin#12]
I can see you guys have done a lot about this project, the README file can provide a good leading function to recognize your code. However, there are still some problems need to fix:
1. After I run the Android interface, it works successfully, it can login and upload the picture, check the history of picture, but  the interface need modify because it is too simple. One more technical small bug is that when I want to login, the login button need to click two times.
2. As for the database, I cannot know the structure of your database, and there should be more database command of it.
3. The recognition part still individual with the Android app, so maybe you guys should spend some time on it to integrate it.
4.There are too less useful code comment especially for the function, maybe a better comment will definitely improve the readability! 
Bess wishes, you have done a lot, I am really looking forward the final project!

**Comment by markshibu** [comment]
Thanks a lot!
