### ISSUE TITLE
Code Review 2

### ISSUE THREAD

**Issue by danielnkq** [mingzicao/601-BSRAPP-CampusPin#13]
Overall there is great improvement in the structure of the repository.

The addition of the Readme file was great as it is now clear what the purpose of this repository is.
i think the addition of the video demo was a nice touch i believe it'll help people see your app in action.

The files in the repository have been put in folders now and aren't just scattered about.
I noticed two folders CampusPin and CampusPin_V1.0. Im tempted to believe that CampusPin was the initial and the latter is an updated version. With this said i don't understand why they need to be separated since GitHub will just update and merge similar file.

The code structure was good. Code was written in an easily read fashion and well commented so even a lay person will know which part of the code does what.

i also found an EC605 file in there. i think you should take it out.

**Comment by markshibu** [comment]
Thanks a lot!
