### ISSUE TITLE
daniel Quartey code review

### ISSUE THREAD

**Issue by danielnkq** [mingzicao/601-BSRAPP-CampusPin#4]
In main.cpp I suggest you take out all the unnecessary lines  of code that have been commented out if you have no further plans for them. Aside this the commenting structure of the code was good and made the code easy to understand and follow. I was unable to run this code on an online compiler because it didn't know the path specified but i'm sure thats just a compiler problem.

there's no read me file attached so it's a bit difficult to ascertain where what goes.

building_class.py was well structured and if main.cpp looked more like this , it'll improve its readability.

**Comment by markshibu** [comment]
Updated Readme File. Please take a look if you want.
